"""Read-only access to Oracle.

Three things live here and nowhere else: the connection pool, the plan estimate
used by the approval policy, and query execution with a hard timeout and a hard
row limit. Both limits are set on the database session rather than trusted to
the query text, because a limit the caller can omit is not a limit.
"""

from __future__ import annotations

import re
import time
from dataclasses import dataclass
from typing import Any

import oracledb


class QueryTimeout(Exception):
    """The query ran longer than its budget and was cancelled."""


class QueryRefused(Exception):
    """The database refused the query: privileges, resource profile, bad SQL."""


@dataclass(frozen=True)
class Plan:
    lines: list[str]
    estimated_rows: int | None
    estimated_cost: float | None


@dataclass(frozen=True)
class Rows:
    columns: list[str]
    rows: list[list[Any]]
    row_count: int
    truncated: bool
    duration_ms: int


class Database:
    def __init__(
        self,
        *,
        user: str,
        password: str,
        dsn: str,
        min_sessions: int = 1,
        max_sessions: int = 6,
    ) -> None:
        # The pool ceiling matches the global concurrency limit: fifteen analysts
        # must not turn into fifteen database sessions.
        self._pool = oracledb.create_pool(
            user=user,
            password=password,
            dsn=dsn,
            min=min_sessions,
            max=max_sessions,
            increment=1,
            getmode=oracledb.POOL_GETMODE_TIMEDWAIT,
            wait_timeout=5000,
        )

    def close(self) -> None:
        self._pool.close(force=True)

    def _connection(self, timeout_seconds: int | None = None):
        connection = self._pool.acquire()
        if timeout_seconds:
            # Enforced by the driver and the server, not by the query text.
            connection.call_timeout = timeout_seconds * 1000
        return connection

    def explain(self, sql: str, *, statement_id: str) -> Plan:
        """Estimate the query without running it.

        EXPLAIN PLAN writes to PLAN_TABLE$, a global temporary table every user
        can write to, so this stays available to a user with no privileges
        beyond CREATE SESSION and SELECT.
        """
        with self._connection(timeout_seconds=15) as connection:
            cursor = connection.cursor()
            # STATEMENT_ID must be a literal: Oracle rejects a bind variable here
            # with ORA-01780. The id is generated by this process and checked
            # against a strict pattern before it is inlined, so it cannot carry
            # anything but hex and an underscore.
            if not re.fullmatch(r"[A-Za-z0-9_]{1,30}", statement_id):
                raise QueryRefused(f"bad statement id: {statement_id!r}")
            try:
                cursor.execute(
                    f"EXPLAIN PLAN SET STATEMENT_ID = '{statement_id}' FOR {sql}"
                )
            except oracledb.DatabaseError as exc:
                raise QueryRefused(_message(exc)) from exc

            cursor.execute(
                """
                SELECT LPAD(' ', 2 * (LEVEL - 1)) || operation ||
                       CASE WHEN options IS NULL THEN '' ELSE ' ' || options END ||
                       CASE WHEN object_name IS NULL THEN '' ELSE ' ' || object_name END
                           AS step,
                       cardinality, cost, id
                FROM plan_table
                WHERE statement_id = :sid
                START WITH id = 0
                CONNECT BY PRIOR id = parent_id AND statement_id = :sid
                ORDER SIBLINGS BY id
                """,
                sid=statement_id,
            )
            fetched = cursor.fetchall()
            lines = [row[0] for row in fetched]
            root = next((row for row in fetched if row[3] == 0), None)
            estimated_rows = int(root[1]) if root and root[1] is not None else None
            estimated_cost = float(root[2]) if root and root[2] is not None else None

            cursor.execute("DELETE FROM plan_table WHERE statement_id = :sid", sid=statement_id)
            connection.commit()

        return Plan(lines=lines, estimated_rows=estimated_rows, estimated_cost=estimated_cost)

    def run(self, sql: str, *, max_rows: int, timeout_seconds: int) -> Rows:
        started = time.monotonic()
        with self._connection(timeout_seconds=timeout_seconds) as connection:
            cursor = connection.cursor()
            cursor.arraysize = min(max_rows, 500)
            try:
                cursor.execute(sql)
                # One row more than allowed, so truncation is detected rather
                # than guessed at.
                fetched = cursor.fetchmany(max_rows + 1)
            except oracledb.DatabaseError as exc:
                message = _message(exc)
                if _is_timeout(exc):
                    raise QueryTimeout(
                        f"Запрос остановлен по таймауту {timeout_seconds} секунд. "
                        "Сузьте период или добавьте фильтр."
                    ) from exc
                raise QueryRefused(message) from exc

            columns = [d.name for d in cursor.description]

        truncated = len(fetched) > max_rows
        rows = [list(row) for row in fetched[:max_rows]]
        return Rows(
            columns=columns,
            rows=rows,
            row_count=len(rows),
            truncated=truncated,
            duration_ms=int((time.monotonic() - started) * 1000),
        )


def _message(exc: oracledb.DatabaseError) -> str:
    error = exc.args[0] if exc.args else None
    text = getattr(error, "message", str(exc)).strip()
    return text.splitlines()[0] if text else str(exc)


def _is_timeout(exc: oracledb.DatabaseError) -> bool:
    error = exc.args[0] if exc.args else None
    code = getattr(error, "code", None)
    # ORA-01013 user requested cancel, raised when call_timeout fires.
    # ORA-03156 driver-side call timeout.
    # ORA-02393 the resource profile's CPU ceiling, which is the same story
    # from the analyst's point of view: the query was too heavy.
    return code in (1013, 3156, 2393)
